@startuml
'https://plantuml.com/class-diagram
package minecraft{
    class LivingEntity
}

abstract class Body{
    - HashMap parts
    + {method} heal logic
    + {method} damage logic
}
class BodyRegistry{
}
abstract class BodyPart{
    - PartLocation location
    - float maxHealth
    - float health
    - int armorSlot
    - attributeModifiers
    + {method}getters and setters
}
abstract class BodyPartModifier{
    - attributeModifiers
}
class BodyPartRegistry{
}
class BodyImpl extends Body{
    + initParts()
    + {method} specific damage logic
}

class OnLivingEntityInitMixin
note right: Calls BodyManager.assignBody()
class BodyManager{
    - assignmentConditions
    + addAssignment()
    + assignBody()
}
class BodyAssignment{
    - Body body
    - LivingEntity[] affectedEntities
    - int priority
    - Predicate shouldUse
}
interface BodyProvider{
    + getBody()
    + setBody()
    + removeBody()
}
abstract class BodyFunction{
    - BodyPart[] parts
    - int minPartNumber
    - float debufThreshold
    - bool isCritical
    + tick()
    - thresholdExceeded()
    - applyDebuf()
}

class PartLocation{}

class PartLocationElement{}

'-------------------------------------------------------------------------'

BodyManager --* "0..*" BodyAssignment
BodyAssignment --* "1" Body

Body --* "0..*" BodyPart
BodyProvider --* "1" Body
LivingEntity --|> BodyProvider
(BodyProvider, LivingEntity) ..  OnLivingEntityInitMixin
BodyRegistry --* Body
BodyPartRegistry --* BodyPart
Body --* BodyFunction
BodyFunction --* BodyPart
BodyPart -* BodyPartModifier
PartLocation --* PartLocationElement
BodyPart --* PartLocation

@enduml